# Site settings
title: Ordina JTech
email: jtech@ordina.nl
description: > # this means to ignore newlines until "baseurl:"
  We build innovative solutions with Java and JavaScript. To support this mission, we have several Competence Centers. From within those Competence Centers, we provide coaching to the employee and expert advice towards our customer. In order to keep in sync with the latest technologies and the latest trends, we frequently visit conferences around the globe.
metadata:
    author: Ordina Nederland
    keywords: Ordina,JTech,Blog,Java,JavaScript,TypeScript,Angular,DevOps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ordina-jtech.github.io" # the base hostname & protocol for your site
twitter_username: ordina
github_username:  ordina-jtech
facebook: ordina
plugins: [jekyll-paginate, jekyll-feed]
# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

# Pagination
paginate: 10

collections:
    # Needed for our job board
    jobs:
        output: true
        permalink: /jobs/:path/
    training:
        output: true
        permalink: /training/:path/
    talks:
        output: true
        permalink: /talks/:path/

defaults:
  - scope:
      path: "jobs"
      type: jobs
    values:
      layout: job
  - scope:
      path: "training"
      type: training
    values:
      layout: training
  - scope:
      path: "talks"
      type: talks
    values:
      layout: talk